version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/resources"
      - "/resources/sharp-bundle"
    schedule:
      interval: "monthly"
    groups:
      sharp:
        patterns:
          - "sharp*"
      dev-dependencies:
        dependency-type: "development"
        exclude-patterns:
          - "sharp*"

  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "monthly"
