version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/resources"
      - "/resources/sharp-bundle"
    schedule:
      interval: "monthly"

  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "monthly"
