version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "monthly"
